### Creating Arrays

In [1]:
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)

arr2d = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])
print(arr2d)

zeroArr = np.zeros(( 3, 4))
print(zeroArr)

oneArr = np.ones((2, 3, 4))
print(oneArr)

[1 2 3 4 5]
[[1 2 3 4]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [5]:
fullArr = np.full((3, 5), 6)
print(fullArr)

eyeArr = np.eye(4)
print("\n",eyeArr)

randArr = np.random.random((2, 3))
print(randArr)

arangeArr = np.arange(10, 100, 15)
print(arangeArr)

linspaceArr = np.linspace(23, 1000, 5)
print(linspaceArr)

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.26176335 0.29191718 0.69201214]
 [0.2389268  0.53728661 0.06704078]]
[10 25 40 55 70 85]
[  23.    267.25  511.5   755.75 1000.  ]


###  Checking Array Properties

In [ ]:
array = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(array)
print("Shape of array:", array.shape)
print("Number of dimensions:", array.ndim)
print("Data type of elements:", array.dtype)
print("Size of each element (in bytes):", array.itemsize)
print("Total number of elements:", array.size)
print("Total size of the array (in bytes):", array.nbytes)

### Changing Data Types


In [6]:
array = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]], dtype = np.float64)
print(array)
print("Data type of elements after change:", array.dtype)

intarr = array.astype(np.int32) # Convert float to int
print(intarr)
print("Data type of elements after converting back to int:", intarr.dtype)


[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Data type of elements after change: float64
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Data type of elements after converting back to int: int32


###  Reshaping and Flattening Arrays

In [37]:
print(array)
print(array.shape)
print(array.reshape(3, 4))
print(array.reshape(2, 6))
array_flat = intarr.flatten()
print(array_flat)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
(4, 3)
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
