In [8]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype = np.int64)
print(arr)
print(arr.dtype)
newarr = arr.astype(np.float64)
print(newarr)
print(newarr.dtype)
print(arr.nbytes)
print(newarr.nbytes)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
int64
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
float64
96
96
