In [42]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [43]:
print(arr)
flat = arr.flatten()
print(flat)
print(arr[1:3, 1:3])


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[5 6]
 [8 9]]


### Indixing

In [44]:
print(flat[5])
print(flat[:5])
print(flat[3:])
print(flat[::2])
print(flat[[2,4,5]])
print(flat[flat % 2 == 0])
print(arr[1:3, 1:3])
print(arr[1])
print(arr[1][1:4])
print(arr[arr >= 5])


6
[1 2 3 4 5]
[ 4  5  6  7  8  9 10 11 12]
[ 1  3  5  7  9 11]
[3 5 6]
[ 2  4  6  8 10 12]
[[5 6]
 [8 9]]
[4 5 6]
[5 6]
[ 5  6  7  8  9 10 11 12]


#### Exercises for Practice

In [45]:
# Create a 3×3 array filled with random numbers and print its shape.
arr = np.random.rand(3,3)
print(arr)
print(arr.shape)

# Convert an array of floats [1.1, 2.2, 3.3] into integers.
floatArr = np.array([1.1, 2.2, 3.3])
intArr = floatArr.astype(int)
print(intArr)

# Use fancy indexing to extract even numbers from  [1, 2, 3, 4, 5, 6].
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Even Numbers:", array[array % 2 == 0])

# Reshape a 1D array of size 9 into a 3×3 matrix.
oneDArr = np.arange(9)
reshapeArr = oneDArr.reshape(3,3)
print(reshapeArr)

# Use boolean masking to filter numbers greater than 50 in an array.
largeArr = np.arange(100)
print(largeArr[largeArr > 50])


[[0.10046263 0.73800889 0.94626693]
 [0.73728153 0.07695532 0.47220312]
 [0.66800382 0.60948253 0.09970025]]
(3, 3)
[1 2 3]
Even Numbers: [2 4 6]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
 99]
