In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print(np.sum(arr, axis=0))  # Sum of each column
print(np.sum(arr, axis=1))  # Sum of each row
print(arr[1][1])
print(arr[0:2, 0:2])  # Slicing the array
print(arr[0:2, 1:2])  # Slicing the array

[12 15 18]
[ 6 15 24]
5
[[1 2]
 [4 5]]
[[2]
 [5]]


In [15]:
arr3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3D)
print(arr3D.ndim)
print(arr3D[1,0,2])  # Accessing element 9
print(arr3D[0:2, 0:1, 1:3]) # Slicing the 3D array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
9
[[[2 3]]

 [[8 9]]]
